---
- name : Updating packages 
  hosts: all
  become : true
  gather_facts: yes

  tasks:
   - name: Updating packages on all machine
     yum:
      name: "*"
      state: latest
     when: ansible_facts ['distrubution'] in ['Amazon']

   - name: yum update
     yum:
      name: "*"
      state: latest
     when: ansible_facts ['distrubution'] in ['Ubuntu']

  