---
- name : Updating packages 
  hosts: all
  become : true
  gather_facts: yes

  tasks:
   - name: Updating yum packages on all machine
     yum:
      name: "*"
      state: latest
     when: ansible_facts ['distribution'] in ['Amazon']

   - name: yum update
     apt:
      name: "*"
      state: latest
     when: ansible_facts ['distribution'] in ['Ubuntu']

- name : nginx playbook
  hosts: webs
  become : true
  gather_facts: yes

  tasks:
   - name: installing nginx 
     yum:
      name: nginx
      state: present
     when: ansible_facts ['distribution'] in ['Amazon']

   - name: installing nginx
     apt:
      name: nginx
      state: present
     when: ansible_facts ['distribution'] in ['Ubuntu']
  