---
- name: Configuring Nginx on web servers
  become: true
  gather_facts: true
  hosts: webs

  tasks:
  - name: Installing Nginx on web-amazon
    yum:
     name: nginx 
     state: "{{ nginx_state }}"
    when: ansible_facts ['distribution'] in ['Amazon']

  - name: Installing Nginx in web-ubuntu
    apt:
     name: nginx
     state: "{{ nginx_state }}"
    when: ansible_facts ['distribution'] in ['Ubuntu']

  - name: Starting Nginx on web-amazon
    service:
     name: nginx
     state: started
    when: nginx_state == "present" 


  - name: Changing Nginx.Conf file
    template:
     src: templates/nginx.conf.j2
     dest: /etc/nginx/nginx.conf
    when: nginx_state == "present" 

    


  - name: Reloading nginx configuration file
    service:
     name: nginx
     state: reloaded
    when: nginx_state == "present"

 



